---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sleep-echo-pipeline
  namespace: python-app
spec:
  params:
    - name: repository
      type: string
    - name: revision
      type: string
    - name: echo-string
      type: string
  tasks:
    - name: sleep-echo
      taskRef:
        name: sleep-echo-task
      params:
        # We have to pass both the url and the rev because Cartographer
        # expects those from any ClusterSourceTemplate. The TaskRun that
        # gets automatically created will have those parameters ONLY IF
        # we list them here.
        - name: source-url
          value: $(params.repository)   # this comes from the 'params' in the spec above ^
        - name: source-revision
          value: $(params.revision)     # This one, too
        - name: echo-string
          value: $(params.echo-string)